version: '3.4'

services:
  send:
    image: send
    build:
      context: node_modules/send
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7000:7000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
